language: python

python:
  - "3.7"

services:
  - docker
  - redis-server

before_install:
  - pip install pipenv==2018.11.26

install:
  - pipenv install --dev --system --deploy
  - python manage.py migrate
  - python manage.py collectstatic

script:
  - python manage.py test
  - coverage run --source='.' manage.py test app.minime

after_success:
  - coveralls
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
  - docker build -t $APP_NAME:$TRAVIS_BUILD_ID .
  - docker tag $APP_NAME:$TRAVIS_BUILD_ID $AWS_ECR_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
