language: python
python:
  - "3.6"
services:
  - redis-server
before_install:
  - pip install pipenv==2018.7.1
install:
  - pipenv install --dev --system --deploy
  - python manage.py migrate
script: python manage.py test
